// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ClgJngP4Tfxu9InHgDt6kwYO7b5g9HU',
    appId: '1:471375608487:web:72cb8657d2d401c6e8b982',
    messagingSenderId: '471375608487',
    projectId: 'longeviva-web-app-dev',
    authDomain: 'longeviva-web-app-dev.firebaseapp.com',
    storageBucket: 'longeviva-web-app-dev.firebasestorage.app',
    measurementId: 'G-EGLWDG5TKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZPr0H8J_gWL41ELH5VbczjHgajFJl81I',
    appId: '1:471375608487:android:7417c85f3a03419fe8b982',
    messagingSenderId: '471375608487',
    projectId: 'longeviva-web-app-dev',
    storageBucket: 'longeviva-web-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxCj3pAiEc8-SBqLv0BHmj_DSqdeC8H6s',
    appId: '1:471375608487:ios:63b8854bddb8d094e8b982',
    messagingSenderId: '471375608487',
    projectId: 'longeviva-web-app-dev',
    storageBucket: 'longeviva-web-app-dev.firebasestorage.app',
    iosBundleId: 'com.example.longevivaAdminV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxCj3pAiEc8-SBqLv0BHmj_DSqdeC8H6s',
    appId: '1:471375608487:ios:63b8854bddb8d094e8b982',
    messagingSenderId: '471375608487',
    projectId: 'longeviva-web-app-dev',
    storageBucket: 'longeviva-web-app-dev.firebasestorage.app',
    iosBundleId: 'com.example.longevivaAdminV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9ClgJngP4Tfxu9InHgDt6kwYO7b5g9HU',
    appId: '1:471375608487:web:a2ef2330f2c85b49e8b982',
    messagingSenderId: '471375608487',
    projectId: 'longeviva-web-app-dev',
    authDomain: 'longeviva-web-app-dev.firebaseapp.com',
    storageBucket: 'longeviva-web-app-dev.firebasestorage.app',
    measurementId: 'G-EJRE4FF53T',
  );
}
